1 html
HuseynBabakhanov/purpleschool pull request #1
Opened 2024-01-07 19:52 UTC by HuseynBabakhanov

2024-01-08 19:59 UTC, Levitinn requested changes

2024-01-08 19:59 UTC, Levitinn commented on 1-Blog/index.html
> +    <p>B</p>
В Мой блог - это один элемент

2024-01-08 19:59 UTC, Levitinn commented on 1-Blog/index.html
> +    <a href="#">Мой блог</a>
все эти ссылки являются навигацией <nav>  а так же, это список который должен быть внутри nav -> ul ->li -> a

2024-01-08 19:59 UTC, Levitinn commented on 1-Blog/index.html
> +    <li>
тег li это элемент списка ul. Не наоборот. Ты перепутал=) и здесь вовсе не нужно использовать список

2024-01-08 19:59 UTC, Levitinn commented on 1-Blog/index.html
> +    <img src="images/avatar.jpg" alt="Аватарка" />
каждый тег img стоит оборачивать в отдельный div, это позволит проще управлять его стилями. здесь и везде в будущем, оборачивай его в див

2024-01-08 19:59 UTC, Levitinn commented on 2-Form/index.html
> +        /><br /><br />
`<br />` лишние, отступы в дальнейшем будут реализованы стилями

2024-01-08 19:59 UTC, Levitinn commented on 2-Form/index.html
> +        <input type="text" id="name" name="name" placeholder="Имя" />
каждый инпут, так же, стоит оборачивать в отдельный див

2024-01-10 13:57 UTC, HuseynBabakhanov commented on 1-Blog/index.html
> +    <a href="#">Мой блог</a>
<nav>
      <ul>
        <li>
          <a href="#">В Мой блог</a>
          <a href="#">HTML и CSS</a>
          <a href="#">Frontend</a>
          <a href="#">Backend</a>
        </li>
      </ul>
    </nav>

2024-01-10 13:58 UTC, HuseynBabakhanov commented on 1-Blog/index.html
> +    <li>
<p>FRONTEND</p>
    <p>12 мая 2024</p>

2024-01-10 13:59 UTC, HuseynBabakhanov commented on 1-Blog/index.html
> +    <img src="images/avatar.jpg" alt="Аватарка" />
<div>
      <img src="images/avatar.png" alt="Аватарка" />
    </div>

    <div>
      <img src="images/main.png" alt="Главное фото" />
    </div>

2024-01-12 06:01 UTC, merged